### ISSUE TITLE
需要一些群组服务器的域名

### ISSUE THREAD

**Issue by hite4044** [SerendipityR-2022/PortScannerForMinecraftServer#1]
你好，我最近在编写一个扫描某服务器所有端口上MC服务器的程序。
为此，我需要一些测试服务器域名来检测我的扫描仪是否工作
我的程序：[https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI](url)

**Comment by SerendipityR-2022** [comment]
很不错的程序哦！我的测试域名都来自这个网站，你可以试试
https://www.mclists.cn/
